In [36]:
from py_gpmf_parser.gopro_telemetry_extractor import GoProTelemetryExtractor
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta
import numpy as np
import pandas as pd

In [37]:
filepath = Path('/Users/charles/github/py-gpmf-parser/GX010022.MP4')

In [50]:
extractor = GoProTelemetryExtractor(filepath)
extractor.open_source()
accl, accl_t = extractor.extract_data("ACCL")
gps5, gps5_t = extractor.extract_data("GPS5")
gps, gps_t = extractor.extract_data("GPS9")
gyro, gyro_t = extractor.extract_data("GYRO")
magn, magn_t = extractor.extract_data("MAGN")
face, face_t = extractor.extract_data("FACE")
facenm, facenm_t = extractor.extract_data("FACE")
corin, corin_t = extractor.extract_data("CORI")
iori, iori_t = extractor.extract_data("IORI")
grav, grav_t = extractor.extract_data("GRAV")
extractor.close_source()

In [39]:
print(accl)

[[11.22781775 -0.68105516  2.19904077]
 [11.28057554 -0.61390887  1.882494  ]
 [11.24220624 -0.46522782  1.52757794]
 ...
 [ 5.91606715  2.17745803 -2.72901679]
 [ 5.48920863  2.3117506  -2.27817746]
 [ 4.89928058  2.27577938 -1.86091127]]


In [40]:

print(gps)

[[ 3.40291867e+01 -1.18372184e+02  4.61030000e+01 ...  7.86777990e+04
   2.27000000e+00  3.00000000e+00]
 [ 3.40291875e+01 -1.18372184e+02  4.59280000e+01 ...  7.86778990e+04
   2.09000000e+00  3.00000000e+00]
 [ 3.40291872e+01 -1.18372184e+02  4.60270000e+01 ...  7.86780000e+04
   2.12000000e+00  3.00000000e+00]
 ...
 [ 3.40293899e+01 -1.18372126e+02  2.05820000e+01 ...  7.88011990e+04
   2.33000000e+00  3.00000000e+00]
 [ 3.40293929e+01 -1.18372126e+02  2.06600000e+01 ...  7.88012990e+04
   2.33000000e+00  3.00000000e+00]
 [ 3.40293957e+01 -1.18372126e+02  2.05680000e+01 ...  7.88013990e+04
   2.33000000e+00  3.00000000e+00]]


In [41]:
print(gyro)

[[ 0.33652822 -0.48136315  0.08626198]
 [ 0.40362087 -0.4515442   0.01916933]
 [ 0.46112886 -0.39936102 -0.04046858]
 ...
 [-0.77742279  0.57933972 -0.08839191]
 [-0.7827476   0.657082   -0.05750799]
 [-0.73801917  0.70074547 -0.05537806]]


In [42]:
# Create subplot with 3 rows for X, Y, Z acceleration
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=('Z-Axis Acceleration', 'X-Axis Acceleration', 'Y-Axis Acceleration'),
    vertical_spacing=0.08,
    shared_xaxes=True
)

# Add X-axis acceleration (row 1)
fig.add_trace(
    go.Scatter(x=accl_t, y=accl[:, 0], 
               mode='lines', 
               name='Accel Z',
               line=dict(color='red', width=1)),
    row=1, col=1
)

# Add Y-axis acceleration (row 2)  
fig.add_trace(
    go.Scatter(x=accl_t, y=accl[:, 1], 
               mode='lines', 
               name='Accel X',
               line=dict(color='green', width=1)),
    row=2, col=1
)

# Add Z-axis acceleration (row 3)
fig.add_trace(
    go.Scatter(x=accl_t, y=accl[:, 2], 
               mode='lines', 
               name='Accel Y',
               line=dict(color='blue', width=1)),
    row=3, col=1
)

# Update layout
fig.update_layout(
    height=800,
    title_text="GoPro Accelerometer Data vs Time",
    showlegend=True
)

# Update x-axis labels
fig.update_xaxes(title_text="Time (seconds)", row=3, col=1)

# Update y-axis labels
fig.update_yaxes(title_text="Acceleration Z (m/s²)", row=1, col=1)
fig.update_yaxes(title_text="Acceleration X (m/s²)", row=2, col=1)
fig.update_yaxes(title_text="Acceleration Y (m/s²)", row=3, col=1)

fig.show()


In [43]:
# Create subplot with 3 rows for X, Y, Z acceleration
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=('Z-Axis Gyro', 'X-Axis Gyro', 'Y-Axis Gyro'),
    vertical_spacing=0.08,
    shared_xaxes=True
)

# Add X-axis acceleration (row 1)
fig.add_trace(
    go.Scatter(x=gyro_t, y=gyro[:, 0], 
               mode='lines', 
               name='Gyro Z',
               line=dict(color='red', width=1)),
    row=1, col=1
)

# Add Y-axis acceleration (row 2)  
fig.add_trace(
    go.Scatter(x=gyro_t, y=gyro[:, 1], 
               mode='lines', 
               name='Gyro X',
               line=dict(color='green', width=1)),
    row=2, col=1
)

# Add Z-axis acceleration (row 3)
fig.add_trace(
    go.Scatter(x=gyro_t, y=gyro[:, 2], 
               mode='lines', 
               name='Gyro Y',
               line=dict(color='blue', width=1)),
    row=3, col=1
)

# Update layout
fig.update_layout(
    height=800,
    title_text="GoPro Accelerometer Data vs Time",
    showlegend=True
)

# Update x-axis labels
fig.update_xaxes(title_text="Time (seconds)", row=3, col=1)

# Update y-axis labels
fig.update_yaxes(title_text="Acceleration Z (m/s²)", row=1, col=1)
fig.update_yaxes(title_text="Acceleration X (m/s²)", row=2, col=1)
fig.update_yaxes(title_text="Acceleration Y (m/s²)", row=3, col=1)

fig.show()

In [44]:
# Let's examine the GPS timestamp data structure first
print("GPS timestamp data shape:", gps_t.shape)
print("GPS timestamp data type:", gps_t.dtype)
print("First few GPS timestamps:", gps_t[:5])
print("GPS timestamp sample:", gps_t[0] if len(gps_t) > 0 else "No data")


GPS timestamp data shape: (1237,)
GPS timestamp data type: float64
First few GPS timestamps: [0.005921 0.106021 0.206121 0.306221 0.406321]
GPS timestamp sample: 0.005921


In [45]:
# plot GPS data

# GPS9 	lat, long, alt, 2D speed, 3D speed, days since 2000, secs since midnight (ms precision), DOP, fix (0, 2D or 3D) 	10 	
#        deg, deg, m, m/s, m/s,-,s,-,- 	GPS returns for HERO13

# Create subplot with 3 rows for X, Y, Z acceleration
fig = make_subplots(
    rows=3, cols=1,
    subplot_titles=('Latitude', 'Longitude', 'Altitude'),
    vertical_spacing=0.08,
    shared_xaxes=True
)

# Add X-axis acceleration (row 1)
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 0], 
               mode='lines', 
               name='Latitude',
               line=dict(color='red', width=1)),
    row=1, col=1
)

# Add Y-axis acceleration (row 2)  
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 1], 
               mode='lines', 
               name='Longitude',
               line=dict(color='green', width=1)),
    row=2, col=1
)

# Add Z-axis acceleration (row 3)
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 2], 
               mode='lines', 
               name='Altitude',
               line=dict(color='blue', width=1)),
    row=3, col=1
)

# Update layout
fig.update_layout(
    height=800,
    title_text="GoPro  LLA Data vs Time",
    showlegend=True
)

# Update x-axis labels
fig.update_xaxes(title_text="Time (seconds)", row=3, col=1)

# Update y-axis labels
fig.update_yaxes(title_text="Latitude", row=1, col=1)
fig.update_yaxes(title_text="Longitude", row=2, col=1)
fig.update_yaxes(title_text="Altitude", row=3, col=1)

fig.show()

In [46]:
# plot gps speed



# GPS9 	lat, long, alt, 2D speed, 3D speed, days since 2000, secs since midnight (ms precision), DOP, fix (0, 2D or 3D) 	10 	
#        deg, deg, m, m/s, m/s,-,s,-,- 	GPS returns for HERO13

fig = make_subplots(
    rows=2, cols=1,
    subplot_titles=('2d speed', '3d speed'),
    vertical_spacing=0.08,
    shared_xaxes=True
)

# Add X-axis acceleration (row 1)
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 3], 
               mode='lines', 
               name='2d speed',
               line=dict(color='red', width=1)),
    row=1, col=1
)

# Add Y-axis acceleration (row 2)  
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 4], 
               mode='lines', 
               name='3d speed',
               line=dict(color='green', width=1)),
    row=2, col=1
)

# Update layout
fig.update_layout(
    height=800,
    title_text="GoPro GPS Speed Data vs Time",
    showlegend=True
)

# Update x-axis labels
fig.update_xaxes(title_text="Time (seconds)", row=3, col=1)

# Update y-axis labels
fig.update_yaxes(title_text="2d speed", row=1, col=1)
fig.update_yaxes(title_text="3d speed", row=2, col=1)

fig.show()


In [47]:
def arrays_to_datetime(days_since_2000, seconds_since_midnight):
    # Reference date: January 1, 2000
    reference_date = datetime(2000, 1, 1)
    
    # Convert to pandas datetime
    datetime_series = pd.to_datetime(reference_date) + \
                     pd.to_timedelta(days_since_2000, unit='D') + \
                     pd.to_timedelta(seconds_since_midnight, unit='s')
    
    return datetime_series

In [48]:
gps_datetime = arrays_to_datetime(gps[:, 5], gps[:, 6])

In [49]:
# days since 2000, secs since midnight (ms precision), DOP, fix (0, 2D or 3D)


fig = make_subplots(
    rows=5, cols=1,
    subplot_titles=('Days since 2000', 'Seconds since midnight', 'DOP', 'Fix', 'datetime'),
    vertical_spacing=0.08,
    shared_xaxes=True
)

# days since 2000
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 5], 
               mode='lines', 
               name='Days since 2000',
               line=dict(color='red', width=1)),
    row=1, col=1
)

# Add Y-axis acceleration (row 2)  
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 6], 
               mode='lines', 
               name='Seconds since midnight',
               line=dict(color='green', width=1)),
    row=2, col=1
)

# DOP
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 7], 
               mode='lines', 
               name='DOP',
               line=dict(color='blue', width=1)),
    row=3, col=1
)

# fix
fig.add_trace(
    go.Scatter(x=gps_t, y=gps[:, 8], 
               mode='lines', 
               name='Fix',
               line=dict(color='purple', width=1)),
    row=4, col=1
)

# datetime
fig.add_trace(
    go.Scatter(x=gps_t, y=gps_datetime, 
               mode='lines', 
               name='datetime',
               line=dict(color='orange', width=1)),
    row=5, col=1
)

# Update layout
fig.update_layout(
    height=800,
    title_text="GoPro GPS  Data vs Time",
    showlegend=True
)

# Update x-axis labels
fig.update_xaxes(title_text="Time (seconds)", row=3, col=1)

# Update y-axis labels
fig.update_yaxes(title_text="Days since 2000", row=1, col=1)
fig.update_yaxes(title_text="Seconds since midnight", row=2, col=1)
fig.update_yaxes(title_text="DOP", row=3, col=1)
fig.update_yaxes(title_text="Fix", row=4, col=1)
fig.update_yaxes(title_text="datetime", row=5, col=1)

fig.show()